set -g default-terminal "screen-256color"
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set -g escape-time 0
set -g status-position bottom
set -g status-justify left
set -g status-left ""
set -g status-right ""

bind r source-file ~/.tmux.conf \; display "Config reloaded!"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# bind v split-window -h -c "#{pane_current_path}"
# bind s split-window -v -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
